In [1]:
## Author: @panthadeep_b
##Created on: 06.Oct.25; 20.57 IST
## Introduction to PyTorch

##Check for GPU
import torch
dev_info = torch.cuda.get_device_name(0);
dev = torch.device("cuda");
print("The device is:", dev_info);

#to check if your GPU driver and CUDA/ROCm is enabled and accessible by PyTorch
torch.cuda.is_available()



The device is: NVIDIA T400 4GB


True

In [23]:
x = torch.tensor([1.0, 2.0, 3.0]);
print('1D Tensor: \n', x);

y = torch.zeros((3, 3));
print('2D Tensor: \n', y);

r = torch.randn(3, 4, 5, device = dev, dtype = torch.float);
print('Random Tensor: \n', r);

1D Tensor: 
 tensor([1., 2., 3.])
2D Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Random Tensor: 
 tensor([[[-1.3800,  1.4234, -0.8630,  0.5071, -0.3255],
         [ 0.6016, -0.2874, -0.2065,  0.6659,  0.0558],
         [-1.1297,  1.1097,  0.4561,  0.3935, -0.4528],
         [ 0.8636, -0.2974, -0.4732,  1.2902,  0.0685]],

        [[ 1.3759, -1.3348, -0.4896,  0.0732,  1.1078],
         [-0.3115, -2.6948,  0.3503,  0.8196,  0.1869],
         [ 0.9433,  1.2005, -0.5427, -0.4314,  2.0096],
         [ 1.8746,  0.8235,  0.5532,  0.6753, -0.3647]],

        [[ 1.8519, -1.0740,  1.4996,  0.6535,  0.0250],
         [-0.5868, -0.2750, -0.4370, -0.1886,  1.8260],
         [-1.2701, -0.6918,  0.3211,  0.6315, -1.8826],
         [ 0.4197,  0.0909,  1.0530, -1.3546,  0.4067]]], device='cuda:0')


In [3]:
##How to create tensors
V_data = [1,2,3,4,5];
V = torch.tensor(V_data);
print("The tensor data is: ", V);

The tensor data is:  tensor([1, 2, 3, 4, 5])


In [4]:
##Create tensor of random data
x = torch.randn((2, 3, 4))
print(x)

tensor([[[ 1.0434,  0.0949, -1.1867,  1.5603],
         [-0.9752,  0.4236,  0.7670,  0.5128],
         [-0.5096, -0.3875, -1.8118,  0.4830]],

        [[ 1.0825, -0.8802,  0.5258, -1.4739],
         [ 0.6044,  0.3206,  0.8386,  0.0125],
         [ 0.2927,  1.5084, -0.0876,  0.3005]]])


In [5]:
##Perform operations using torch

arr1 = torch.tensor([1.0, 2.0]);
arr2 = torch.tensor([3.0, 4.0]);

arr = arr1 + arr2;
print("The add matrix result is: ", arr);

e1 = arr1.view(2,1);
print("e1: ", e1);

e2 = arr2.view(1,2);
print("e2: ", e2);

mat_mul = torch.matmul(e1, e2);
print("The matrix multiplcation of e1, e2 is: ", mat_mul);


The add matrix result is:  tensor([4., 6.])
e1:  tensor([[1.],
        [2.]])
e2:  tensor([[3., 4.]])
The matrix multiplcation of e1, e2 is:  tensor([[3., 4.],
        [6., 8.]])


In [6]:
%pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126
Note: you may need to restart the kernel to use updated packages.


In [7]:
%pwd

'/home/nitrcs/Documents/test-code/PyTorch'

In [8]:
%ls

data/                   __pycache__/  torch_intro.ipynb
Gradient-descent.ipynb  torch_int.py  torch_vision.ipynb


In [9]:
import torch
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])
